# Generated by Django 3.2.2 on 2021-05-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessage',
            table='user_messages',
        ),
    ]
